- name: Trial
  id: sandbox
  internal_id: free
  title: FREE
  subtitle: 1-day Free Trial
  features:
    - Unlimited deploys
    - 10GB Bandwidth
    - 100MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: Open Source
  id: open-source
  internal_id: open_source
  title: FREE
  subtitle: We support open source projects
  features:
    - Unlimited deploys
    - 100GB Bandwidth / Month
    - 100MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 50MB Memory
  id: 50-MB
  internal_id: first
  title: $0.50
  subtitle: per month
  features:
    - Unlimited deploys
    - 100GB Bandwidth / Month
    - 50MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 100MB Memory
  id: 100-MB
  internal_id: second
  title: $1.00
  subtitle: per month
  features:
    - Unlimited deploys
    - 200GB Bandwidth / Month
    - 100MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 200MB Memory
  id: 200-MB
  internal_id: third
  title: $2.00
  subtitle: per month
  features:
    - Unlimited deploys
    - 400GB Bandwidth / Month
    - 200MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 500MB Memory
  id: 500-MB
  internal_id: fourth
  title: $5.00
  subtitle: per month
  features:
    - Unlimited deploys
    - 1000GB Bandwidth / Month
    - 500MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 1GB Memory
  id: 1-GB
  internal_id: fifth
  title: $10.00
  subtitle: per month
  features:
    - Unlimited deploys
    - 2000GB Bandwidth / Month
    - 1024MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: 2GB Memory
  id: 2-GB
  internal_id: sixth
  title: $20.00
  subtitle: per month
  features:
    - Unlimited deploys
    - 4000GB Bandwidth / Month
    - 2048MB Memory
    - 1000MB Disk Storage
    - Custom domain or your-subdomain.openode.io
  button: 
    url: /admin/billing
    text: Order

- name: On Demand
  features:
    #- 'Extra CPUs: $5 / CPU / Month'
    - 'Extra Storage: $0.15 / 1 GB / Month'
    - 'Exceeding Bandwidth: $0.015 / GB'
    #- 'Snapshot: $0.05 / GB'
  button: 
    url: /admin/billing
    text: Order

                        